# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -c release
    - name: Compress archive
      run: tar -czf ${{ github.ref_name }}.tar.gz -C .build/release/spm
    - name: Relese
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.ref_name }}.tar.gz
    - name: Run tests
      run: swift test -v
