# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -c release -v
    - name: Compress archive
      if: startsWith(github.ref, 'refs/tags/')  # 仅在推送标签时压缩归档
      run: tar -czf ${{ github.ref_name }}.tar.gz -C .build/release .
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')  # 仅在推送标签时执行 Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.ref_name }}.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
